# General App Settings
spring.application.name=timesheet-backend

# The path to the database file (this will create timesheet.db in the project folder)
spring.datasource.url=jdbc:sqlite:timesheet.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# JPA / Hibernate Settings
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update

# Optional: Debugging (Shows SQL in the console)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true 
spring.jackson.serialization.indent_output=true
